/** Barrel export — one import site for every store. */
export { useAuthStore } from './authStore'
export { useUserStore } from './userStore'
export { useProductStore } from './productStore'
export { useCategoryStore } from './categoryStore'
export { useCartStore } from './cartStore'
export { useWishlistStore } from './wishlistStore'
export { useOrderStore } from './orderStore'
export { useAddressStore } from './addressStore'
export { usePaymentStore } from './paymentStore'
export { useCouponStore } from './couponStore'
export { useNotificationStore } from './notificationStore'
export { useSearchStore } from './searchStore'
export { usePrescriptionStore } from './prescriptionStore'
export { useSupportStore } from './supportStore'
export { useLoadingStore } from './loadingStore'
export { useUiStore, toast } from './uiStore'
export { useCatalogStore } from './catalogStore'
